### ISSUE TITLE
raincat-admin 登录404

### ISSUE THREAD

**Issue by YangAnLin** [yu199195/Raincat#31]
![image](https://user-images.githubusercontent.com/30170561/47360037-e662b300-d700-11e8-8a80-97194a1a1462.png)

配置
application.yml
```yml
server:
   port: 8888
#   context-path: /admin

spring:
   application:
      name: raincat-admin
   profiles:
     active: db

tx:
  admin :
    userName : admin
    password : admin
  redis:
    hostName: localhost
    port : 6379
    #password:
    cluster : false
      # nodes: 127.0.0.1:70001;127.0.1:7002
      # redirects: 20

accept:
  apps:
    server:
      type[0]: property
      type[1]: eureka
      type[2]: unaccept
    eureka:
      url: http://localhost:9003/eureka
      intervalTime: 30
```

application-db.yml
```yml
recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   db:
      driver :  com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.100.205:3306/tx?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: root
```
